name: CI Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            APP_VERSION=${{ github.sha }}
          tags: |
            leohurin/lab-teste1:${{ github.sha }}
            leohurin/lab-teste1:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: leandrosanttos007/lab-teste1-gitops
          token: ${{ secrets.GIT_TOKEN }}
          path: gitops

      - name: Update image in Deployment
        working-directory: gitops
        run: |
          sed -i "s|image: .*|image: leohurin/lab-teste1:${{ github.sha }}|" k8s/deployment.yaml

          if git diff --quiet; then
            echo "Nenhuma mudança no manifesto, pulando commit."
            exit 0
          fi

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "update image to ${{ github.sha }}"
          git pull --rebase origin main
          git push
